require("keymaps")
require("options")
require("plugins.lazy")
require("plugins.catppuccin")
require("plugins.keymaps")
require("plugins.treesitter")
require("plugins.tree")
require("plugins.bufferline")
require("plugins.comments")
require("plugins.nvim-lspconfig")
require("plugins.cord-config")
-- require("plugins.debug.lua")
